### ISSUE TITLE
NELL and Wiki Noisy Datasets

### ISSUE THREAD

**Issue by gawainx** [SongW-SW/REFORM#1]
Experiments from the origin paper "REFORM: Error-Aware Few-Shot Knowledge Graph Completion" are conducted in NELL, Wiki and FB15k-237 datasets. Since the selection of the noisy data are important to reimplement the experiments, would you please provide the other two datasets (Wiki and NELL) with noisy data (ERROR rate 0.05, 0.1, 0.15 and 0.2) ?

**Comment by SongW-SW** [comment]
Thank you for your comment. I have uploaded the dataset files and corresponding codes to process it.
