### ISSUE TITLE
'Trainer' object has no attribute 'connections'

### ISSUE THREAD

**Issue by Garethyu** [SongW-SW/REFORM#2]
Hello,I Obey your file which called readme.But firstly it says, "name 'num_class' is not defined",and I set "num_class=2".However,it says "'Trainer' object has no attribute 'connections'",I do not know how to solve this problem,and would you like to help me,thanks a lot.

**Comment by SongW-SW** [comment]
Hi, sorry for the inconvenience here. I found that I previously delete one line by accident. I have updated the file train.py, where one line "degrees=self.build_connection(max_=self.max_neighbor)" is added. Really sorry for the inconvenience!

**Comment by Garethyu** [comment]
Well, I trained it successfully!Thanks a lot!
